application: eawkassirer
version: 1
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: jinja2
  version: latest
- name: markupsafe                                                              
  version: latest
  
handlers:
- url: /stylesheets
  static_dir: stylesheets
  
- url: /js
  static_dir: js
  
- url: /static
  static_dir: static

- url: /resume
  static_files: static/resume.pdf
  upload: static/resume.pdf

- url: /blog/rss.xml
  static_files: static/rss-feed.xml
  upload: static/rss-feed.xml
  mime_type: application/atom+xml

- url: /.*
  script: main.app
